/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      colors: {
        "tertiary-container": "#00855b",
        "outline-variant": "#c2c6d6",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "surface-variant": "#e1e3e4",
        "on-tertiary-fixed-variant": "#005236",
        "surface-bright": "#f8f9fa",
        "surface-container-high": "#e7e8e9",
        "primary-container": "#2170e4",
        "secondary-fixed": "#d9e3f4",
        "surface-container-highest": "#e1e3e4",
        "on-primary-container": "#fefcff",
        "error-container": "#ffdad6",
        "surface-container-low": "#f3f4f5",
        "on-tertiary-container": "#f5fff6",
        "inverse-primary": "#adc6ff",
        "primary-fixed": "#d8e2ff",
        "on-secondary": "#ffffff",
        "on-background": "#191c1d",
        "surface": "#f8f9fa",
        "surface-tint": "#005ac2",
        "on-secondary-container": "#596372",
        "on-error": "#ffffff",
        "tertiary-fixed": "#6ffbbe",
        "error": "#ba1a1a",
        "on-surface-variant": "#424754",
        "secondary-container": "#d6e0f1",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d9dadb",
        "tertiary": "#006947",
        "on-secondary-fixed-variant": "#3e4755",
        "on-primary-fixed": "#001a42",
        "on-tertiary-fixed": "#002113",
        "outline": "#727785",
        "on-primary": "#ffffff",
        "on-surface": "#191c1d",
        "primary-fixed-dim": "#adc6ff",
        "inverse-surface": "#2e3132",
        "tertiary-fixed-dim": "#4edea3",
        "primary": "#0058be",
        "secondary": "#555f6d",
        "background": "#f8f9fa",
        "on-error-container": "#93000a",
        brand: {
          50: '#eff6ff',
          100: '#dbeafe',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
        },
      },
    },
  },
  plugins: [],
};
